name: "test sign"

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: test sign script

    steps:
      - name: checkout code
        uses: actions/checkout@v1

      - name: get latest build tools version
        id: sdk
        run: |
          echo version=$(ls $ANDROID_HOME/build-tools | tail -n 1) >> $GITHUB_OUTPUT

      - name: set up environment
        run: npm i --include=dev
  
      - name: test script
        run: npm run test

      - name: get signing key
        id: key
        run: echo text=$(cat __tests__/test_key_b64.txt) >> $GITHUB_OUTPUT

      - name: sign apk
        uses: ./
        env:
          BUILD_TOOLS_VERSION: ${{steps.sdk.outputs.version}}
        with:
          alias: test_key
          keyPassword: android
          keyStorePassword: android
          releaseDirectory: __tests__/apk
          signingKeyBase64: ${{steps.key.outputs.text}}

      - name: sign aab
        uses: ./
        env:
          BUILD_TOOLS_VERSION: ${{steps.sdk.outputs.version}}
        with:
          alias: test_key
          keyPassword: android
          keyStorePassword: android
          releaseDirectory: __tests__/aab
          signingKeyBase64: ${{steps.key.outputs.text}}